services:
  # client
  hostA:
    build: .
    image: srft-runtime:latest
    container_name: hostA-172.31.64.201
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      srft-net:
        ipv4_address: 172.31.64.201
    command: ["bash", "-c", "/etc/init.d/openbsd-inetd start && tail -f /dev/null"]

  # server
  hostB:
    build: .
    image: srft-runtime:latest
    container_name: hostB-172.31.77.14
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      srft-net:
        ipv4_address: 172.31.77.14
    command: ["bash", "-c", "/etc/init.d/openbsd-inetd start && tail -f /dev/null"]

networks:
  srft-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
