services:
  hostA:
    image: handsonsecurity/seed-ubuntu:large-arm
    container_name: hostA-10.0.1.10
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      srft-net:
        ipv4_address: 10.0.1.10
    command: ["bash", "-c", "/etc/init.d/openbsd-inetd start && tail -f /dev/null"]

  hostB:
    image: handsonsecurity/seed-ubuntu:large-arm
    container_name: hostB-10.0.1.20
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      srft-net:
        ipv4_address: 10.0.1.20
    command: ["bash", "-c", "/etc/init.d/openbsd-inetd start && tail -f /dev/null"]

networks:
  srft-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
